name: Deploy MultiDocker
on:
  push:
    branches:
      - main # master or main? check

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t danielmaomitch/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true danielmaomitch/react-test npm test

      - run: docker build -t danielmaomitch/multi-client ./client
      - run: docker build -t danielmaomitch/multi-nginx ./nginx
      - run: docker build -t danielmaomitch/multi-server ./server
      - run: docker build -t danielmaomitch/multi-worker ./worker

      - run: docker push danielmaomitch/multi-client
      - run: docker push danielmaomitch/multi-nginxthu
      - run: docker push danielmaomitch/multi-server
      - run: docker push danielmaomitch/multi-worker